default: &default
  adapter: postgresql
  encoding: unicode
development:
  <<: *default
  database: idle_development

test:
  <<: *default
  database: idle_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  pool: 6
